### PR TITLE
Upgrade packages in "flutter_markdown"

### PR DESCRIPTION
**Pull request by nilsreichardt**
Executed `flutter pub upgrade --major-versions`

### CODE REVIEW

**Comment by Jonas-Sander** [comment]
Do we absolutely need to upgrade? Since there are several breaking changes in `markdown` we might break stuff in subtle and unforeseeable ways.

**Comment by nilsreichardt** [comment]
It was required because `flutter_markdown` depends on `path` and a one of the dependencies I upgraded in https://github.com/SharezoneApp/sharezone-app/pull/844 required a newer version of `path`

**Comment by Jonas-Sander** [comment]
But `path` isn't even upgraded in this PR?

> It was required because `flutter_markdown` depends on `path` and a one of the dependencies I upgraded in [SharezoneApp/sharezone-app#844](https://github.com/SharezoneApp/sharezone-app/pull/844) required a newer version of `path`

**Comment by nilsreichardt** [comment]
> But `path` isn't even upgraded in this PR?

It's used by a package that I upgraded (not sure which package it was)

**Comment by Jonas-Sander** [comment]
Just FYI, I'm gonna try to insert our custom logic into the code for newest version of the package. Probably won't finish it today though. If it is way more work than expected then we can use this dependency upgrade instead. WDYT?

**Comment by nilsreichardt** [comment]
Note: I already included this PR already in the pull request https://github.com/SharezoneApp/sharezone-app/pull/844 and tested it - everything worked with the privacy policy. You can test it here: https://alpha.web.sharezone.net

**Comment by Jonas-Sander** [comment]
Closing since we merged #2

**Pull request closed without merging**
